### ISSUE TITLE
Allow using relative paths for settings

### ISSUE THREAD

**Issue by flying-sheep** [xojs/vscode-linter-xo#105]
There’s two possible ways to go about this:

- Allow `./blah` relative paths in addition to `file://` URLs, or
- Implement variable substitution (`${workspaceFolder}`): Since inexplicably VS Code doesn’t export the mechanism it uses itself (microsoft/vscode#2809), we could use a subset of [the code PythonVSCode uses](https://github.com/DonJayamanne/pythonVSCode/blob/e8b109c2f21e56128620abd881e04fded9b7fd76/src/client/common/variables/systemVariables.ts)

One step in the resolution of #71

**Comment by flying-sheep** [comment]
@sindresorhus which one would you prefer? I could do a quick PR.

**Comment by Spence-S** [comment]
I'm willing to support/merge this if you want to make a PR @flying-sheep seems like a reasonable use case to me.

The only line that would need to be changed is this: 
https://github.com/xojs/vscode-linter-xo/blob/master/server/server.js#L464

I don't think we should use the same variable substitution that vscode uses, because I don't think we need to support any token other that workspace folder. Maybe a token like? 
`"path": "WORKSPACE_FOLDER/path/to/xo"`

A relative path would be fine too - it just needs to be clear in the docs that if you supply an absolute path it must be in file uri format.

**Comment by flying-sheep** [comment]
I’d prefer a relative path to a custom placeholder. The `${workspaceFolder}` idea was because it’s familiar, but so is using a relative path (e.g. for `eslint.nodePath`)

**Comment by Spence-S** [comment]
sounds good @flying-sheep - I will take care of this later today If I don't see a PR.

**Comment by Spence-S** [comment]
@flying-sheep this is published now - I went ahead an added a couple of lines to deprecate the file uri and made the option take an absolute path or a relative path because I felt this made more sense. Thanks for your help!

**Comment by flying-sheep** [comment]
great, thank you!
