### ISSUE TITLE
feat: support monorepos by allowing nested folders to act as the xo root folder.

### ISSUE THREAD

**Issue by kiikoh** [xojs/vscode-linter-xo#111]
This comes up for me if I want to have a react project in a client folder as well as a server folder both open, and using different configurations. 

I think the expected behavior should be to walk up the folder structure from the file that is currently open stopping at the first package.json it reaches.

**Comment by Spence-S** [comment]
How do you handle this with the xo cli? This is just not the way xo works. -- the way to handle a monorepo in the documentation is to put a single config at the root and use overrides. see https://github.com/xojs/xo#monorepo 
--- I think your use case would need to be better supported by the cli for me to support it here, but if you feel differently I am open to ideas and will accept PRs.

**Comment by kiikoh** [comment]
OK, I think you are right here, XO was giving me a hard time as well, it might be an issue for XO, or not at all, wasn't aware of the monorepos

**Comment by kiikoh** [comment]
Hey, I've tried working with the monorepos and I can't seem to find the correct usage of it anywhere online. How can I set up xo in the root of the monorepo, and then extend the configuration in the "app" level package.json's? Basically, I have a react and express server and I want to have the react plugins for the front-end only

**Comment by papb** [comment]
Hello, I am not in the real situation described here, but after reading the thread I wonder why you started talking about monorepos. Consider a much simpler example: you have two completely unrelated Git repositories of Node.js projects that happen to be cloned next to each other in a folder in your PC. And then you opened only one VSCode window, on this parent folder. Sometimes you work on project A, sometimes on project B, but always with this same VSCode window, for whatever reason. What OP said should just work:

> I think the expected behavior should be to walk up the folder structure from the file that is currently open stopping at the first package.json it reaches.

And for this case, to me, the question of _"How do you handle this with the xo cli"_ is answered with: there's nothing to handle, each project has its repository and will run `xo` from its CI normally.

What am I missing?

**Comment by kiikoh** [comment]
Yeah, I agree I was not completely satisfied with the answer I received either, I still haven't figured out a way to get it working exactly as I'd have liked it to.

**Comment by Spence-S** [comment]
> How can I set up xo in the root of the monorepo, and then extend the configuration in the "app" level package.json's?

You cannot. If I am understanding your question correctly, this is not supported by xo at all. If you want one instance of VSCode and to have multiple folders open with different versions of xo and different configurations, you can use vscodes "multiroot" workspaces. -- vscode-linter-xo does support those and we go to great lengths to cache the versions and give good performance in these scenarios. 

You can start multiroot workspaces by using the "add folder to workspace" command in vscode. This is the closest thing to what you are asking for. 

> What OP said should just work:

> > I think the expected behavior should be to walk up the folder structure from the file that is currently open stopping at the first package.json it reaches.

I am somewhat open to supporting this with a configuration ONLY. I will not try to autodetect what folder is your xo root. That is a lot of work and it is not part of the native LSP folder management provided by VSCode. However, I would be open to supplying a configuration of xo root folders.  

see https://github.com/Microsoft/vscode-eslint#settings-options see the `eslint.workingDirectories` option. I would be open to provide a limited subset of that option for the use cases being described here. However, I cannot promise how quickly I will get to this. I think there are still other more important things to support. 

Note that for mono-repos, as much as I am an xo fan boy, using raw eslint often times makes more sense, as xo is just not designed for a great monorepo experience. I personally don't use mono repos at all, ever, if I can avoid it. 

Despite the arguments of how `xo` _should_ work (everyone has differing opinions on this). The way it works right now, is to have 1 configuration, in a folder, with a package.json and node_modules folder and linting in any child folder can only ever come from that 1 configuration and xo instance. That is how the cli works. That is how this extension works. The configuration cannot be merged with other configurations. Period. 

What we would be supporting here, with this request, is to extend the extension to pick up xo in any random place if the above conditions are met (a folder with an xo config and node_modules child folder with an instance of xo and all of xos deps). This request is somewhat reasonable really, but the implementation will likely be difficult and have lots of edge cases. AND it still won't make everyone happy so that is why I think we should only support a configured portion of folders, at least at first. Maybe down the road this could extend out to "autodetect" if a folder is an xo root, but not initially.

As always, I accept PRs and love contributions. If you love xo and you love monorepos and you want a better integration, I am happy to help you architect the solution if you want to take the time to implement it yourselves.

Note: that we'd need to support this on a per workspace folder instance. So potentially now you have a multiroot workspace, which means we are supporting a different xo per "root". Each "root" would now need to support multiple "user roots" (which is the configured option I am open to support). So we would need to cache xo for each one, have update logic for each one, etc... I am not sure the effect this would have on request queueing as well 😅 .

**Comment by Spence-S** [comment]
release 3.12.0 now allows for xo to be resolved from anywhere and is no longer needed in a workspace. All it needs is to find a parent directory where xo is installed.
