### ISSUE TITLE
VSCode extesion is totally broken

### ISSUE THREAD

**Issue by gabriel-ribeiro-wow** [xojs/vscode-linter-xo#136]

**Comment by spence-s** [comment]
I use this extension daily and it is not broken. 

I would be happy to help if you further describe your issue. You need to ensure that the xo library is installed in your project and available in the node_modules folder for this extension to work. 

You can also open the extension tab at the bottom of vscode and share the output I would be happy to direct you to the fix for your use case, or, if needed fix whatever bug is causing it to not work for you.

Closing until more information is shared.
