### ISSUE TITLE
xo.enable is only detected on config change and not on startup

### ISSUE THREAD

**Issue by easrng** [xojs/vscode-linter-xo#139]
I have a project that uses node and xo, with a subfolder that uses deno and deno's linter. When I open the subfolder, which has a vscode config like `{"deno.enable": true, "xo.enable": false}`, xo still reports errors. If I change it to `"xo.enable": true` and then back to `"xo.enable": false`, xo disables itself properly.

**Comment by spence-s** [comment]
Hello - I am not sure I understand the problem here entirely. Having nested vscode configurations isn't something I am really aware of. It's likely the best way to solve this issue is to ignore the subfolder you don't want to lint in the xo configuration or add a `.eslintignore` file. 

see: https://github.com/xojs/xo?tab=readme-ov-file#ignores

Let me know if this will work for you.

**Comment by easrng** [comment]
No, I open the subfolder as a separate vscode workspace.

**Comment by spence-s** [comment]
Should be fixed as of v3.19 let me know if you have any more issues
