### ISSUE TITLE
Add links to rule explanations?

### ISSUE THREAD

**Issue by wmertens** [xojs/vscode-linter-xo#15]
Not sure if this is possible, but it would be nice to be able to go to a rule definition (like the github issue or eslint docs) when eslint marks something.

So if I see `no-use-extend-native` it somehow links to https://github.com/dustinspecker/eslint-plugin-no-use-extend-native/blob/master/readme.md

**Comment by SamVerschueren** [comment]
That would really be a very nice addition. It can be opened when using <kbd>Cmd</kbd> + click or something.

I guess it would be easier to implement if we redirect to the `npm` webpage. For instance to https://www.npmjs.com/package/eslint-plugin-no-use-extend-native. This way we don't have to fetch the repository of that rule. We can start with implementing this and if it looks like it's not enough, we can always improve on that by caching ruleId + GH repo. What do you think?

I'm not entirely sure if this can be implemented in an extension though.

@bpasero Care to chime in?

**Comment by darkred** [comment]
The ability to add links to diagnostic errors has been added in VSCode since v1.42 (Jan 2020) : see [here](https://code.visualstudio.com/updates/v1_42#_adding-links-to-diagnostic-errors)

E.g. here is a screenshot of how the related rules of the problems are rendered by this extension vs the [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) vscode extension:
![2021-08-30_180348](https://user-images.githubusercontent.com/723651/131360581-051ebcca-84af-4ae1-98fc-b5d30483b7c6.jpg)

**Comment by Spence-S** [comment]
I currently have this as a WIP - along with other features mentioned in the [roadmap.](#95) This particular feature needs a [patch in xo](https://github.com/xojs/xo/issues/590) and also needs some good internal caching strategies to ensure performance. So its just a matter of finding the time. PRs welcome!

**Comment by Spence-S** [comment]
After doing some further research on this - I found that xo primarily relies on the package https://www.npmjs.com/package/eslint-rule-docs  which I am using to add rule definition links as well. No need to add this directly to xo.
